[package]
entrypoint = "start"

[dependencies]
"php/php-32" = "=8.3.2102"

[command]
name = "start"
module = "php/php-32:php"
runner = "wasi"

[command.annotations.wasi]
cwd = "/app"
main-args = [
  "-S",
  "0.0.0.0:8080",
  "-t",
  "/app",
  "index.php"
]
